### ISSUE TITLE
Can .. be used instead

### ISSUE THREAD

**Issue by kenchris** [zenparsing/es-function-bind#10]
It looks more similar to . and Dart uses it as well.

Though it might be a problem with 1..toString()

**Comment by zenparsing** [comment]
Technically we could use "..", but I don't think it's visually distinct enough.  We want it to look pleasing, but obviously different from property lookup.

**Comment by zloirock** [comment]
`..` more interesting as cascade operator like in Dart or LiveScript.
```js
[2, 7, 1, 8]
  ..push(3)
  ..shift()
  ..sort(); // => [1,3,7,8]
```

**Comment by bmeck** [comment]
Just remember that `...` is the spread operator. Consider this:

```
[..other_fn_that_is_iterable]
```

vs
 
```
[...other_fn_that_is_iterable]
```

**Comment by rymohr** [comment]
Would have loved to use `&` over either of these but [since that one's out](https://github.com/zenparsing/es-function-bind/issues/23) my vote's for sticking with `::`

Too much potential for confusion and I'd prefer to see `..` reserved for ranges `1..10`

**Comment by zenparsing** [comment]
Agreed, let's stick with `::`.
