### ISSUE TITLE
Dynamically named virtual methods?

### ISSUE THREAD

**Issue by gsklee** [zenparsing/es-function-bind#14]
Is dynamically named virtual methods somewhere on the road map? Something like this would be really handy and make it parallel with "real" methods in terms of features:

```javascript
const assign = function(...s) {
  return Object.assign(this, ...s);
};

const name = 'assign';

console.log(
  {x: 1}::[name]({y: 2})
);

// {"x":1,"y":2}
```

**Comment by nathggns** [comment]
Variable variables aren't a thing in ES6 at all are they? If not then this couldn't be a simple syntactical transform.

**Comment by zenparsing** [comment]
This is basically `eval` which we want to avoid.

**Comment by bergus** [comment]
You can always use property lookup for dynamic names - limiting ("whitelisting") the available methods to only that available on the object is a desirable side effect.
```
const methods = {assign}; // and more
                          // use {__proto__:null, assign} to be safe
let x = {x: 1};
let name = "assign";
x::(methods[name])({y: 2});
console.log(x);
```

**Comment by gsklee** [comment]
@bergus Good idea, thanks! :+1:
