### ISSUE TITLE
Method extraction?

### ISSUE THREAD

**Issue by ljharb** [zenparsing/es-function-bind#2]
Why would `Promise.resolve(123).then(::console.log);` not be `Promise.resolve(123).then(console::log);`? To me, it makes more sense to have `a::b` as sugar for `b.bind(a)` and `a::b(…)` as sugar for `b.call(a, …)` - if it's `::a.b`, then what exactly is being bound in `::a.b.c` etc?

**Comment by zenparsing** [comment]
Hi @ljharb !

`console::log` would be equivalent to `log.bind(console)`, which is of course not what you want.  You are exactly right that `a::b` is sugar (almost) for `b.bind(a)`.

In the case of `a::b()`, it's still just sugar (almost) for `b.bind(a)()`, except that it can be transparently optimized by the engine to a direct function call like `b.call(a)`.

In the case of `::a.b.c`, we evaluate it like `(temp = a.b, temp.c.bind(temp))` where `temp` is just some temporary (and invisible) variable.

So for `console.log`, we want `::console.log`, which is more-or-less equivalent to `console.log.bind(console)`.

**Comment by ljharb** [comment]
Ah, ok - so `::a.b…y.z` is sugar for `a.b…y::a.b…y.z`. That does make sense, and I think might warrant a special section calling it out (since it's not what I expected initially).

Thanks for clearing it up!
