### ISSUE TITLE
Example: Trine

### ISSUE THREAD

**Issue by jussi-kalliokoski** [zenparsing/es-function-bind#20]
Hi, just wanted to let you know that I just published a utility library taking advantage of this proposal, called Trine: https://github.com/jussi-kalliokoski/trine

It performs the things that your proposed `itertools` library would, and much more.

Hopefully this will get the proposal moving forward toward standardization. :)

**Comment by zenparsing** [comment]
Cool, and thanks!

Replied to your post at https://esdiscuss.org/topic/example-of-real-world-usage-of-function-bind-syntax

**Comment by zenparsing** [comment]
Doing some cleanup here and closing a bunch of issues.  Thanks @jussi-kalliokoski !
