### ISSUE TITLE
Allow super references in unary bind expressions

### ISSUE THREAD

**Issue by zenparsing** [zenparsing/es-function-bind#21]
We currently throw a runtime error if the operand is a super reference.  We can probably remove this restriction though, as it seems pretty clear what the semantics would be.  Given something like:

```js
class C extends B {
    foo() {
        let fn = ::super.foo;
    }
}
```

The function `fn` would be `B.prototype.foo` bound to the current `this` value.

**Comment by bergus** [comment]
+1 for this.
If not, is it possible to make this a compile time error?

**Comment by zenparsing** [comment]
Leaving it a syntax error for now.

**Comment by bergus** [comment]
Can we re-open this please? It seems to be a rather trivial and maybe unimportant change, but one that should definitely be made.

**Comment by zenparsing** [comment]
Just added support in 0533fdae49940be8fed3407bb6d7852ee0f53de9 .  Good?

Thanks for bringing this back up.

**Comment by bergus** [comment]
LGTM after a quick glance. Thanks!
