### ISSUE TITLE
binding with parameters

### ISSUE THREAD

**Issue by dubert** [zenparsing/es-function-bind#22]
I read through all the issues, but I'm not sure if they answer my question (I think this one is related https://github.com/zenparsing/es-function-bind/issues/15)

I’m binding `::this.onPressRow` so it becomes `this.onPressRow.bind(this)`

If I wanted  `this.onPressRow.bind(this, true)` how would I format that using `::`?

**Comment by RangerMauve** [comment]
What you want are partially applied parameters which is [still not entirely formalized](https://github.com/zenparsing/es-function-bind/issues/15)

**Comment by zenparsing** [comment]
This proposal doesn't cover partially applied parameters.
