### ISSUE TITLE
:: conflicts with E4X

### ISSUE THREAD

**Issue by XeCycle** [zenparsing/es-function-bind#27]
The operator `::` is already used in E4X.  It's true that E4X is deprecated and we rarely hear real world usage of it, but [js2-mode](https://github.com/mooz/js2-mode) provides editor support, so when [implementing this](https://github.com/mooz/js2-mode/pull/273) I had to partially drop E4X support.

I think it better to discuss here whether or not to continue with `::` and to be incompatible with E4X; btw `..` as suggested by #10 also conflicts.

@dgutov is the active collaborator there, who may have an idea whether E4X support is actually used by anyone.

**Comment by XeCycle** [comment]
A not-so-serious suggestion: `.*` in C++ is similar to this in functionality.

**Comment by shovon** [comment]
From the looks of it, @zenparsing, the champion behind the operator, [will not be supporting it](https://github.com/zenparsing/es-function-bind/issues/24#issuecomment-141102543).

Instead, he's proposing "function pipelining".

Something like:

```javascript
// Letting `foo`, `bar`, and `baz` be functions that return an array

arrayOfNumbers
  ->foo(el => el*2)
  ->bar(el => el*3)
  ->baz(el => el - 3)
```

You can read about it at issue #26.

**Comment by zenparsing** [comment]
Let's not worry about E4X for now.  Thanks!
