### ISSUE TITLE
Add explanatory note on method extraction with extended member expressions

### ISSUE THREAD

**Issue by zenparsing** [zenparsing/es-function-bind#3]
Explain the behavior of something like:

```js
(::a.b.c.d)
```

**Comment by ckknight** [comment]
Given that `::` is lower-precedence than `.`, am I correct in assuming that the following expressions are equivalent?

    ::a.b.c

and

    ::(a.b).c

Rather than

    (::a.b).c

Which would at least violate the principle of least surprise for me.

**Comment by zenparsing** [comment]
@ckknight That's right, and it makes sense if you think of `::` in this case like any other unary prefix operator.

For example, these are equivalent:

```js
typeof a.b.c;
typeof (a.b).c;
```

But they are not equivalent to:

```js
(typeof a.b).c;
```

On the other hand, my feeling is that the prefix form of `::` is just kinda weird in general and I'm not surprised that you find it surprising.  : )

**Comment by RReverser** [comment]
What about
```javascript
var f = obj::a.b.c;
```
Is it equivalent to
```javascript
var f = a.bind(obj).b.c
```
rather than
```javascript
var f = a.b.c.bind(obj)
```
?

**Comment by zenparsing** [comment]
@RReverser 

Dot `.` always binds tighter than `::`, so your example would be equivalent to 

```js
var f = (a.b.c).bind(obj);
```

Which is what esdown outputs.  If you go to http://zenparsing.github.io/esdown/repl/ and type in:

```js
.translate var f = obj::a.b.c
```

I'm wondering though, if having both the unary form and binary form is too confusing, and if one should win out, which would it be?

**Comment by RReverser** [comment]
I do see benefits from both forms, so wouldn't really drop any (and would even add the one from #5), it's just that they seem to have different rules which confuses a bit.

Also, it would be really good to use #4 and limit unary form only to `MemberExpression`s.

**Comment by impinball** [comment]
Actually, it doesn't really surprise me that much. It appears that it acts more like this:

```js
::a.b
a::a.b
a.b.bind(a)

::a.b.c
a.b::a.b.c
(a.b).c.bind(a.b)

::a.b.c.d
a.b.c::a.b.c.d
(a.b.c).d.bind(a.b.c)
```

That's exactly what I would expect to see with the unary form. And as for having two different forms for the same operator, I don't see the problem.

Now, I do agree that the right hand side for the unary form should be exclusively limited to `MemberExpression`s, since there exist absolutely no use case for anything else.
