### ISSUE TITLE
Why bind to `this` and not pass as an argument?

### ISSUE THREAD

**Issue by rstacruz** [zenparsing/es-function-bind#31]
`this` is something that is mostly used in cases of prototypal inheritance, which is somewhat counter-intuitive to functional-programming-like approaches.

Instead of `a::b()` passing `a` as `this` to the `b()` function, why not pass it as the first parameter? that is:

```js
"hello there world"
  :: titlecase()
  :: take(11)
  :: reverse()
  //=> "erehT olleH"

function titlecase (string) { ... }
function take (string, count) { return string.substr(0, count) }
function reverse (string) { return string.reverse() }
```

This is something that exists in [elixir](http://elixir-lang.org/) as the [pipe operator](http://elixir-lang.org/getting-started/enumerables-and-streams.html#the-pipe-operator).

**Comment by benjamingr** [comment]
This has been discussed over and over, both here and in ESDiscuss. Please read previous issues before opening new ones. https://github.com/zenparsing/es-function-bind/issues/19

**Comment by benjamingr** [comment]
In your case: 

```
function take (count) { return this.substr(0, count) }
function reverse () { return this.split("").reverse().join(""); /* yours was broken*/ }
```
Etc.
