### ISSUE TITLE
Should unary form have a static restriction?

### ISSUE THREAD

**Issue by zenparsing** [zenparsing/es-function-bind#4]
Should the unary form have a static (or even runtime) restriction such that the operand must be a reference type (basically, a property access)?

**Comment by ckknight** [comment]
I'd say yes, otherwise what would `::foo` represent on its own?

**Comment by zenparsing** [comment]
Without a restriction, it would bind `foo` to `undefined`.  Such a binding ought to be written as `undefined::foo` though, so an error make sense.

**Comment by zenparsing** [comment]
@RReverser I've written up the early error rule similar to the early error rule for "delete", so that the operand can be parenthesized.  If that looks good, we'll eventually need to update the parser to allow things like:

```
::((foo.bar))
```

**Comment by RReverser** [comment]
@zenparsing My implementation already allows things like that.

**Comment by RReverser** [comment]
So yeah, let's go ahead and resolve this!
