### ISSUE TITLE
Add test suite

### ISSUE THREAD

**Issue by UltCombo** [zenparsing/es-function-bind#7]
It would be nice to have a conformance test suite for implementators to test their implementations.
Something simple like Mocha tests (or even just assertions through Node's built-in `assert` module) would do.

**Comment by zenparsing** [comment]
Agreed.

**Comment by zenparsing** [comment]
The babel tests are sufficient for now.

https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-function-bind

When this moves forward, we can create a new issue for creating the spec tests.
